export './src/api/index.dart';
export './src/pagination.dart';

// Generated code - do not modify by hand

export './src/graphql/fragments.gql.dart'
    show Fragment$AIFeedback,
        Fragment$AIFeedbackInterface,
        Fragment$AIFeedbackPart,
        Fragment$AnswerMaterialResponse,
        Fragment$AuthInfo,
        Fragment$ConversationCharacter,
        Fragment$ConversationDetails,
        Fragment$ConversationTurn,
        Fragment$ConversationUpdate,
        Fragment$DetailedMaterial,
        Fragment$DetailedMaterial$aiFeedbacks,
        Fragment$DetailedMaterial$details,
        Fragment$DetailedMaterial$details$$ConversationDetails,
        Fragment$DetailedMaterial$details$$QuizDetails,
        Fragment$DetailedMaterial$details$$StoryDetails,
        Fragment$DetailedMaterial$turns,
        Fragment$DetailedStage,
        Fragment$DetailedStage$stagePart,
        Fragment$DetailedSupportedLanguage,
        Fragment$Journey,
        Fragment$Levels,
        Fragment$Material,
        Fragment$MaterialDetails,
        Fragment$MaterialDetails$$ConversationDetails,
        Fragment$MaterialDetails$$QuizDetails,
        Fragment$MaterialDetails$$StoryDetails,
        Fragment$MaterialStatusses,
        Fragment$MeAdmin,
        Fragment$MiniDetails,
        Fragment$MiniDetails$$ConversationDetails,
        Fragment$MiniDetails$$QuizDetails,
        Fragment$MiniDetails$$StoryDetails,
        Fragment$ModelSet,
        Fragment$PageInfo,
        Fragment$PublicUser,
        Fragment$QuestionItem,
        Fragment$QuizDetails,
        Fragment$QuizPrelude,
        Fragment$QuizPreludeItem,
        Fragment$QuizQuestion,
        Fragment$Stage,
        Fragment$StagePart,
        Fragment$StagePartDocumentation,
        Fragment$StagePartMaterial,
        Fragment$StageSentence,
        Fragment$StageWord,
        Fragment$StoryDetails,
        Fragment$StoryPart,
        Fragment$SupportedLanguage,
        Fragment$SupportedLocale,
        Fragment$UserAnswer,
        Fragment$UserDoc,
        Fragment$UserDocExplanation,
        Fragment$UserDocTemplate;

export './src/schema.graphqls.dart'
    show Enum$AIFeedbackPartType,
        Enum$AIFeedbackType,
        Enum$Domains,
        Enum$FeedbackCategory,
        Enum$FeedbackStatus,
        Enum$FeedbackType,
        Enum$MaterialCompStatus,
        Enum$MaterialConvStatus,
        Enum$MaterialFeedbackStatus,
        Enum$MaterialGenStatus,
        Enum$MaterialType,
        Enum$Providers,
        Enum$QuizPreludeItemType,
        Enum$QuizQuestionType,
        Enum$StagePartType,
        Enum$StageStatus,
        Enum$StoryPartType,
        Enum$UserDocExplanationType,
        Enum$UserDocExplanationUI,
        Enum$__DirectiveLocation,
        Enum$__TypeKind,
        Input$AddUserInputInput,
        Input$AnswerMaterialInput,
        Input$ChangePasswordRequest,
        Input$CreateJourneyInput,
        Input$CreateMaterialInput,
        Input$DocumentationInput,
        Input$FeedbackRequest,
        Input$GenMaterialInput,
        Input$LoginAppleRequest,
        Input$LoginEmailRequest,
        Input$LoginGoogleRequest,
        Input$LoginPhoneRequest,
        Input$PaginationInput,
        Input$RegisterEmailRequest,
        Input$RegisterPhoneRequest,
        Input$ResendVerifyEmailRequest,
        Input$ResetPasswordRequest,
        Input$SetDeviceIdInput,
        Input$SetFcmTokenInput,
        Input$SetForwardedFromInput,
        Input$StartConversationInput,
        Input$UpdateJourneyInput,
        Input$UploadingFile,
        Input$UploadingHsl,
        Input$VerifyEmailRequest,
        Input$VerifyForgotPasswordRequest;

