include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
linter:
  rules:
    prefer_relative_imports: true
analyzer:
  exclude:
    - "**/*.graphql.dart"
    - "**/*.graphqls.dart"
    - "**/*.gql.dart"
