name: sign
description: Basic state management base for dart. Sign inspired QT framework signal-slot architecture.
version: 0.0.3
repository: "https://github.com/Mehmetyaz/sign"
homepage: "https://github.com/Mehmetyaz/sign"

environment:
  sdk: 3.8.0-133.0.dev

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
